clf_positions = ['UsingIPAddress1', 'URLlengthRule1', 'TinyService', 'checkArrobaURL',
       'checkRedirectURL', 'checkDashDomain', 'checkSubDomainMulSubDomain',
       'checkHTTPSDomainURL', 'GoogleIndex', 'StatisticalReports',
       'numDotsURL', 'NumDotSubDomain', 'NumDashURL', 'NumDashDomain',
       'checkTildeSymbolURL', 'NumUnderscoreURL', 'NumHashURL',
       'NumNumericCharsURL', 'NoHTTPS', 'DomainInSubdomains', 'DomainInPaths',
       'HostnameLenth', 'NumSensitiveWords', 'NumArrobaURL', 'KnowLTD',
       'get_PositionTLD', 'BrandNameURL', 'numDots_URLRule4', 'SpecialSymbol4',
       'URLlengthRule4', 'SuspiciousInURL', 'httpCountInURL',
       'BrandNameDomain', 'NumNumericChars_Domain',
       'NumNumericChars_Subdomain', 'RandomDomain', 'RandomString',
       'DomainLength', 'SubdomainLength', 'checkWWW', 'checkCOM',
       'numInterrogation', 'numEqual', 'numArroba', 'checkAlexa',
       'AvaregeWordLength', 'LongestWordLength', 'ShortestWordLength',
       'StandardDerivation', 'AdjacentWordCount', 'AverageAdjacentWordLength',
       'SeparatedWordCount', 'OtherWordsCount', 'RandomWordCount',
       'KeywordCount', 'BrandNameCount', 'TargetBrandNameCount',
       'TargetKeywordCount', 'SimilarBrandNameCount', 'SimilarKeywordCount',
       'ConsecutiveCharacterRepeat', 'URLofAnchorRule1', 'statusBarCost',
       'SubmittingEmailTo', 'DisablingRightClick', 'ServerFormHandler',
       'EmbeddedBrandName', 'URLofAnchorCat', 'InsecureForm',
       'RelativeFormAction', 'ExtFormAction', 'AbnormalFormAction',
       'FrequentDomainNameMismatch', 'PopUpWindow', 'ImagesOnlyInForm',
       'PctExtResourceUrls', 'IframeOrFrame', 'LinksMetaScript', 'checkTitle',
       'FakeLoginForm', 'Copied_CSS', 'IdentityKeywords', 'URLofAnchorRule4',
       'CheckDataURI', 'ForeignhyperlinksRule1', 'FaviconD',
       'Foreignhyperlinks', 'Numberofwebpages', 'ForeignhyperlinksRule4',
       'Nohyperlinkfeature', 'Copyrightfeatures', 'LinksMetaScriptRule1',
       'IFrameRedFrameBorder', 'IFrameExternalSRC', 'NumberRedirect']
